CREATE TABLE Creditcard (
	num INT NOT NULL,
    fname VARCHAR(20) NOT NULL,
	lname VARCHAR(20) NOT NULL,
    PRIMARY KEY(num)
)

CREATE TABLE Book (
bid VARCHAR(20) NOT NULL,
title VARCHAR(60) NOT NULL,
price INT NOT NULL,
category VARCHAR(60) NOT NULL,
quan INT NOT NULL,
PRIMARY KEY(bid)
);

CREATE TABLE Address (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
street VARCHAR(100) NOT NULL,
province VARCHAR(20) NOT NULL,
country VARCHAR(20) NOT NULL,
zip VARCHAR(20) NOT NULL,
phone VARCHAR(20),
PRIMARY KEY(id)
);

CREATE TABLE VisitEvent (
day varchar(8) NOT NULL,
bid varchar(20) not null,
eventtype varchar(20) NOT NULL,
FOREIGN KEY(bid) REFERENCES Book(bid)
);

CREATE TABLE PO (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
month int NOT NULL,
lname VARCHAR(20) NOT NULL,
fname VARCHAR(20) NOT NULL,
status VARCHAR(20)  NOT NULL,
address INTEGER NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (address) REFERENCES Address (id) ON DELETE CASCADE
);

CREATE TABLE POItem (
id INTEGER NOT NULL,
bid VARCHAR(20) NOT NULL,
quan INTEGER NOT NULL,
price INTEGER NOT NULL,
PRIMARY KEY(id,bid),
FOREIGN KEY(id) REFERENCES PO(id) ON DELETE CASCADE,
FOREIGN KEY(bid) REFERENCES Book(bid) ON DELETE CASCADE
);


CREATE TABLE Account (
login VARCHAR(20) NOT NULL,
address INTEGER NOT NULL,
fname VARCHAR(20) NOT NULL,
lname VARCHAR(20) NOT NULL,
pass VARCHAR(20) NOT NULL,
PRIMARY KEY(login,address),
FOREIGN KEY (address) REFERENCES Address (id) ON DELETE CASCADE
);