CREATE TABLE Account (
login VARCHAR(20) NOT NULL,
address INT NOT NULL,
fname VARCHAR(20) NOT NULL,
lname VARCHAR(20) NOT NULL,
pass VARCHAR(200) NOT NULL,
PRIMARY KEY(login),
FOREIGN KEY (address) REFERENCES Address (id) ON DELETE CASCADE
);
