CREATE TABLE Review (
rid INTEGER PRIMARY KEY,
bid VARCHAR(20) NOT NULL,
login VARCHAR(20) NOT NULL,
rev VARCHAR(200) NOT NULL,
rating INTEGER CHECK (rating >= 0 and rating <= 5),
FOREIGN KEY(bid) REFERENCES Book(bid) ON DELETE CASCADE,
FOREIGN KEY(login) REFERENCES Account(login) ON DELETE CASCADE
);